---
deployment:
  tasks:
    - export DEPLOYPATH=/home/corywaga/public_html/
    - /bin/rm -f /home/corywaga/public_html/index.html /home/corywaga/public_html/style.css /home/corywaga/public_html/study-planner.html /home/corywaga/public_html/cursor.png /home/corywaga/public_html/websiteLogo1.png
    - /bin/rm -rf /home/corywaga/public_html/blog /home/corywaga/public_html/market\ microstructure /home/corywaga/public_html/papers
    - /bin/cp -R ./app.py ./passenger_wsgi.py ./requirements.txt ./website $DEPLOYPATH
    - /bin/mkdir -p /home/corywaga/public_html/tmp
    - /usr/bin/touch /home/corywaga/public_html/tmp/restart.txt
